<a href="https://colab.research.google.com/github/satty0104/pytorch/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
Scaler = StandardScaler()
x_train = Scaler.fit_transform(x_train)
x_test = Scaler.transform(x_test)

In [8]:
x_train

array([[ 0.85587165,  0.6335806 ,  0.79662954, ...,  1.27457484,
         0.51394466, -0.44660154],
       [ 0.15840527,  0.17626402,  0.11723692, ...,  0.7047748 ,
         0.21073652, -0.08198506],
       [-0.39734484,  1.05082306, -0.36833135, ...,  0.86735774,
         0.78472413,  1.0999142 ],
       ...,
       [ 0.21120153,  0.19512243,  0.17284557, ..., -0.19474952,
        -0.85940987, -0.99465512],
       [-1.18456486, -0.87273537, -1.161762  , ..., -0.74813931,
        -0.64375916,  0.47848579],
       [-0.34176983,  2.24833247, -0.37598762, ..., -0.75345745,
        -0.85454557, -0.6317319 ]])

In [9]:
y_train

264    M
16     M
64     M
559    B
47     M
      ..
165    B
347    B
495    B
524    B
554    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [13]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
# 1. torch.tensor




x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32)



# Key Points:
# Creates a new tensor: A new tensor is created, and the data is copied from the source x_train or x_test.
# Data type conversion: You can specify the dtype explicitly (e.g., torch.float32), and it will ensure the new tensor has the specified data type.
# No link to the original data: The resulting tensor does not share memory with the original NumPy array. Changes to the tensor do not affect the NumPy array, and vice versa.



In [15]:
# torch.from_numpy

# Key Points:
# Creates a tensor that shares memory: The tensor shares the underlying memory with the original NumPy array.
# No data type conversion: The tensor will have the same data type as the original NumPy array. If the NumPy array has a different type (e.g., float64), you may need to explicitly cast it afterward.
# Linked data: Changes to the tensor will reflect in the original NumPy array, and vice versa.




x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

When to Use?
#Use torch.tensor if:

You want to ensure a specific data type for the tensor.

You don’t want changes in the tensor to affect the original NumPy array.

You need a tensor independent of the original NumPy data.


#Use torch.from_numpy if:

You want a quick tensor conversion and don’t need to explicitly set the dtype.

You need the tensor and NumPy array to share data and reflect changes in each other.

In [16]:
x_train_tensor.shape


torch.Size([455, 30])

# Defining the model

In [23]:
class Myann():

  def __init__(self, X):

    self.weights=torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad=True)
    self.bias=torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #calculate loss
    loss = -(y_train_tensor* torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss



In [32]:
learning_rate = 0.01
epochs = 1000

In [33]:
model = Myann(x_train_tensor)


for i in range(epochs):

  #forward pass
  y_pred = model.forward(x_train_tensor)


  #loss calculation

  loss = model.loss_function(y_pred, y_train_tensor)

  #backward pass
  loss.backward()


  #parameters update

  with torch.no_grad():
    model.weights -=learning_rate * model.weights.grad
    model.bias-= learning_rate * model.bias.grad

    #zero gradient
    model.weights.grad.zero_()
    model.bias.grad.zero_()


    #print loss
    print(f'Epoch: {i+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.5909568368044154
Epoch: 2, Loss: 3.5792934650800405
Epoch: 3, Loss: 3.5676449825896386
Epoch: 4, Loss: 3.556011512052693
Epoch: 5, Loss: 3.5443931764739456
Epoch: 6, Loss: 3.532790099144787
Epoch: 7, Loss: 3.5211710123897
Epoch: 8, Loss: 3.5093774486210454
Epoch: 9, Loss: 3.4975151425659106
Epoch: 10, Loss: 3.485642059561595
Epoch: 11, Loss: 3.473607462659443
Epoch: 12, Loss: 3.4615893433328275
Epoch: 13, Loss: 3.4495878352994414
Epoch: 14, Loss: 3.437577487039103
Epoch: 15, Loss: 3.4254251942183718
Epoch: 16, Loss: 3.4132901838458385
Epoch: 17, Loss: 3.4011725948091662
Epoch: 18, Loss: 3.3890725664864116
Epoch: 19, Loss: 3.3768928288256186
Epoch: 20, Loss: 3.364624963348048
Epoch: 21, Loss: 3.3523279201653375
Epoch: 22, Loss: 3.339883181473618
Epoch: 23, Loss: 3.327457545716841
Epoch: 24, Loss: 3.3150511644019236
Epoch: 25, Loss: 3.3026566285988816
Epoch: 26, Loss: 3.289984381621575
Epoch: 27, Loss: 3.2772312185833243
Epoch: 28, Loss: 3.2644984163828314
Epoch: 29, Lo

In [34]:
model.bias

tensor([-0.4731], dtype=torch.float64, requires_grad=True)

In [38]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.95).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6228070259094238
